### ISSUE TITLE
Expander python module

### ISSUE THREAD

**Issue by elio-bufi** [orcmkit/ORCmKit#6]
Goodmorning, I am very interested in the ORCmKIT python version since I want to use it for research purposes for parametric optimization of ORC cycle parameters. However, it seems that the python version lacks of the Expander module in the /ORCsim folder and, of course, of the ExpanderClass() which is of importance for the other modules. Where could I find a compatible version of this module ? Thank You very much,

Elio

**Comment by davideziviani** [comment]
Elio! I have added the file that was missing. Please try it and let me know if any other issues with this ExpanderClass. If not I will close the issue.

**Comment by elio-bufi** [comment]
Thank You very much, it seems to work well now!

**Comment by davideziviani** [comment]
If you use the tool for research purposes and you plan to publish, please cite ORCSim according to my publication on [Energies](http://www.mdpi.com/1996-1073/9/6/389)

**Comment by mcekwonu** [comment]
Hi how can get the GUI in python. I want to use it for research
